### ISSUE TITLE
slurmdb_jobs().get() returns nothing when sacct returns jobs

### ISSUE THREAD

**Issue by treydock** [PySlurm/pyslurm#154] opened 2019-12-18 18:26 UTC
#### Details

* Slurm Version: 19.05.3-2
* Python Version: 2.7
* Cython Version: 0.29.14
* PySlurm Branch: 19-05-0
* Linux Distribution: RHEL 7.7

#### Issue

If I execute `pyslurm.slurmdb_jobs().get()` I get an empty dictionary but the same user running `sacct` gets jobs.

```
>>> import pyslurm
>>> pyslurm.slurmdb_jobs().get()
{}
```

```
# sacct
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
2            hostname.+      batch    pzs0708          2     FAILED      1:0 
2.batch           batch               pzs0708          2     FAILED      1:0 
3            hostname.+      batch    pzs0708          2  COMPLETED      0:0 
3.batch           batch               pzs0708          2  COMPLETED      0:0 
4            sleep.sba+      batch    pzs0708          2     FAILED      2:0 
4.batch           batch               pzs0708          2     FAILED      2:0 
5            sleep.sba+      batch    pzs0708          2    TIMEOUT      0:0 
5.batch           batch               pzs0708          2  CANCELLED      0:9 
```

Both were run as root on the slurmctld host and also tried from slurmdbd host. The debug logs on slurmdbd show a job query is received:

```
Dec 18 13:25:19 slurmdbd01-test slurmdbd[10729]: debug2: Opened connection 8 from 10.20.0.34
Dec 18 13:25:19 slurmdbd01-test slurmdbd[10729]: debug:  REQUEST_PERSIST_INIT: CLUSTER:pitzer VERSION:8704 UID:0 IP:10.20.0.34 CONN:8
Dec 18 13:25:19 slurmdbd01-test slurmdbd[10729]: debug2: acct_storage_p_get_connection: request new connection 1
Dec 18 13:25:19 slurmdbd01-test slurmdbd[10729]: debug2: Attempting to connect to dbsystest01.<OMIT>:3306
Dec 18 13:25:19 slurmdbd01-test slurmdbd[10729]: debug2: DBD_GET_JOBS_COND: called
Dec 18 13:25:19 slurmdbd01-test slurmdbd[10729]: 8(as_mysql_jobacct_process.c:585) query#012select t1.account, t1.admin_comment, t1.array_max_tasks, t1.array_task_str, t1.constraints, t1.cpus_req, t1.derived_ec, t1.derived_es, t1.exit_code, t1.flags, t1.id_array_job, t1.id_array_task, t1.id_assoc, t1.id_block, t1.id_group, t1.id_job, t1.pack_job_id, t1.pack_job_offset, t1.id_qos, t1.id_resv, t3.resv_name, t1.id_user, t1.id_wckey, t1.job_db_inx, t1.job_name, t1.kill_requid, t1.mem_req, t1.node_inx, t1.nodelist, t1.nodes_alloc, t1.partition, t1.pri
Dec 18 13:25:19 slurmdbd01-test slurmdbd[10729]: 8(as_mysql_jobacct_process.c:585) query#012select t1.account, t1.admin_comment, t1.array_max_tasks, t1.array_task_str, t1.constraints, t1.cpus_req, t1.derived_ec, t1.derived_es, t1.exit_code, t1.flags, t1.id_array_job, t1.id_array_task, t1.id_assoc, t1.id_block, t1.id_group, t1.id_job, t1.pack_job_id, t1.pack_job_offset, t1.id_qos, t1.id_resv, t3.resv_name, t1.id_user, t1.id_wckey, t1.job_db_inx, t1.job_name, t1.kill_requid, t1.mem_req, t1.node_inx, t1.nodelist, t1.nodes_alloc, t1.partition, t1.pri
Dec 18 13:25:19 slurmdbd01-test slurmdbd[10729]: 8(as_mysql_jobacct_process.c:585) query#012select t1.account, t1.admin_comment, t1.array_max_tasks, t1.array_task_str, t1.constraints, t1.cpus_req, t1.derived_ec, t1.derived_es, t1.exit_code, t1.flags, t1.id_array_job, t1.id_array_task, t1.id_assoc, t1.id_block, t1.id_group, t1.id_job, t1.pack_job_id, t1.pack_job_offset, t1.id_qos, t1.id_resv, t3.resv_name, t1.id_user, t1.id_wckey, t1.job_db_inx, t1.job_name, t1.kill_requid, t1.mem_req, t1.node_inx, t1.nodelist, t1.nodes_alloc, t1.partition, t1.pri
Dec 18 13:25:19 slurmdbd01-test slurmdbd[10729]: 8(as_mysql_jobacct_process.c:585) query#012select t1.account, t1.admin_comment, t1.array_max_tasks, t1.array_task_str, t1.constraints, t1.cpus_req, t1.derived_ec, t1.derived_es, t1.exit_code, t1.flags, t1.id_array_job, t1.id_array_task, t1.id_assoc, t1.id_block, t1.id_group, t1.id_job, t1.pack_job_id, t1.pack_job_offset, t1.id_qos, t1.id_resv, t3.resv_name, t1.id_user, t1.id_wckey, t1.job_db_inx, t1.job_name, t1.kill_requid, t1.mem_req, t1.node_inx, t1.nodelist, t1.nodes_alloc, t1.partition, t1.pri

```

**Comment by giovtorres** [comment] 2019-12-22 21:37
Duplicate of #153 . Closing.

**Closed by giovtorres** 2019-12-22 21:37 UTC
Labels: Bug, Duplicate
