### ISSUE TITLE
Upgrade to support Slurm 20.02

### ISSUE THREAD

**Issue by bhipple** [PySlurm/pyslurm#172] opened 2020-03-10 23:33 UTC
https://github.com/SchedMD/slurm/releases
Upstream Slurm has had a 20.02 release and we're interested in upgrading to it in NixPkgs.  What's involved to get `pyslurm` to support the new release?

**Comment by giovtorres** [comment] 2020-03-13 00:52
My test container is broken between 19.05 and 20.02 and I haven't had a chance to troubleshoot :sob:

**Comment by laurentvm** [comment] 2020-03-18 11:00
Naive attempt to change only SLURM_VERSION to  "20.02

`
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_6config___get’:
pyslurm/pyslurm.c:12144:75: error: ‘slurm_ctl_conf_t’ has no member named ‘acctng_store_job_comment’
     __pyx_t_1 = __Pyx_PyInt_From_uint16_t(__pyx_v_self->__pyx___Config_ptr->acctng_store_job_comment); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 518, __pyx_L1_error)
                                                                           ^
pyslurm/pyslurm.c:12288:86: error: ‘slurm_ctl_conf_t’ has no member named ‘checkpoint_type’
     __pyx_t_1 = __pyx_f_7pyslurm_5slurm_stringOrNone(__pyx_v_self->__pyx___Config_ptr->checkpoint_type, __pyx_kp_s_); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 530, __pyx_L1_error)
                                                                                      ^
pyslurm/pyslurm.c:12420:75: error: ‘slurm_ctl_conf_t’ has no member named ‘disable_root_jobs’
     __pyx_t_1 = __Pyx_PyInt_From_uint16_t(__pyx_v_self->__pyx___Config_ptr->disable_root_jobs); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 541, __pyx_L1_error)
                                                                           ^
pyslurm/pyslurm.c:12510:75: error: ‘slurm_ctl_conf_t’ has no member named ‘fast_schedule’
     __pyx_t_1 = __Pyx_PyInt_From_uint16_t(__pyx_v_self->__pyx___Config_ptr->fast_schedule); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 548, __pyx_L1_error)
                                                                           ^
pyslurm/pyslurm.c:12717:86: error: ‘slurm_ctl_conf_t’ has no member named ‘job_ckpt_dir’
     __pyx_t_2 = __pyx_f_7pyslurm_5slurm_stringOrNone(__pyx_v_self->__pyx___Config_ptr->job_ckpt_dir, __pyx_kp_s_); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 565, __pyx_L1_error)
                                                                                      ^
pyslurm/pyslurm.c:12954:90: error: ‘slurm_ctl_conf_t’ has no member named ‘licenses_used’
     __pyx_t_1 = __pyx_f_7pyslurm_7pyslurm___get_licenses(__pyx_v_self->__pyx___Config_ptr->licenses_used); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 591, __pyx_L1_error)
                                                                                          ^
pyslurm/pyslurm.c:14390:75: error: ‘slurm_ctl_conf_t’ has no member named ‘track_wckey’
     __pyx_t_1 = __Pyx_PyInt_From_uint16_t(__pyx_v_self->__pyx___Config_ptr->track_wckey); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 716, __pyx_L1_error)
                                                                           ^
pyslurm/pyslurm.c:14438:75: error: ‘slurm_ctl_conf_t’ has no member named ‘use_pam’
     __pyx_t_1 = __Pyx_PyInt_From_uint16_t(__pyx_v_self->__pyx___Config_ptr->use_pam); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 720, __pyx_L1_error)
                                                                           ^
pyslurm/pyslurm.c:14453:75: error: ‘slurm_ctl_conf_t’ has no member named ‘use_spec_resources’
     __pyx_t_2 = __Pyx_PyInt_From_uint16_t(__pyx_v_self->__pyx___Config_ptr->use_spec_resources); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 721, __pyx_L1_error)
                                                                           ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_checkpoint_able’:
pyslurm/pyslurm.c:23843:3: warning: implicit declaration of function ‘slurm_checkpoint_able’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_checkpoint_able(__pyx_v_JobID, __pyx_v_JobStep, (&__pyx_v_Time));
   ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_checkpoint_enable’:
pyslurm/pyslurm.c:24080:3: warning: implicit declaration of function ‘slurm_checkpoint_enable’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_checkpoint_enable(__pyx_v_JobID, __pyx_v_JobStep);
   ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_checkpoint_disable’:
pyslurm/pyslurm.c:24317:3: warning: implicit declaration of function ‘slurm_checkpoint_disable’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_checkpoint_disable(__pyx_v_JobID, __pyx_v_JobStep);
   ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_checkpoint_create’:
pyslurm/pyslurm.c:24562:3: warning: implicit declaration of function ‘slurm_checkpoint_create’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_checkpoint_create(__pyx_v_JobID, __pyx_v_JobStep, __pyx_v_MaxWait, __pyx_v_ImageDir);
   ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_checkpoint_requeue’:
pyslurm/pyslurm.c:24837:3: warning: implicit declaration of function ‘slurm_checkpoint_requeue’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_checkpoint_requeue(__pyx_v_JobID, __pyx_v_MaxWait, __pyx_v_ImageDir);
   ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_checkpoint_restart’:
pyslurm/pyslurm.c:25386:3: warning: implicit declaration of function ‘slurm_checkpoint_restart’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_checkpoint_restart(__pyx_v_JobID, __pyx_v_JobStep, __pyx_v_Stick, __pyx_v_ImageDir);
   ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_checkpoint_complete’:
pyslurm/pyslurm.c:25669:3: warning: implicit declaration of function ‘slurm_checkpoint_complete’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_checkpoint_complete(__pyx_v_JobID, __pyx_v_JobStep, __pyx_v_BeginTime, __pyx_v_ErrorCode, __pyx_v_ErrMsg);
   ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_checkpoint_task_complete’:
pyslurm/pyslurm.c:25973:3: warning: implicit declaration of function ‘slurm_checkpoint_task_complete’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_checkpoint_task_complete(__pyx_v_JobID, __pyx_v_JobStep, __pyx_v_TaskID, __pyx_v_BeginTime, __pyx_v_ErrorCode, __pyx_v_ErrMsg);
   ^
pyslurm/pyslurm.c: In function ‘__pyx_pf_7pyslurm_7pyslurm_74slurm_checkpoint_error’:
pyslurm/pyslurm.c:26357:3: warning: implicit declaration of function ‘slurm_checkpoint_error’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_checkpoint_error(__pyx_v_JobID, __pyx_v_JobStep, (&__pyx_v_ErrorCode), (&__pyx_v_Msg));
   ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_slurm_checkpoint_tasks’:
pyslurm/pyslurm.c:26556:3: warning: implicit declaration of function ‘slurm_checkpoint_tasks’ [-Wimplicit-function-declaration]
   __pyx_v_errCode = slurm_checkpoint_tasks(__pyx_v_JobID, __pyx_v_JobStep, __pyx_v_BeginTime, __pyx_v_ImageDir, __pyx_v_MaxWait, __pyx_v_NodeList);
   ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_3job_get_job_ptr’:
pyslurm/pyslurm.c:29906:39: error: ‘slurm_job_info_t’ has no member named ‘pack_job_id’
     __pyx_t_6 = (__pyx_v_self->_record->pack_job_id != 0);
                                       ^
pyslurm/pyslurm.c:29916:66: error: ‘slurm_job_info_t’ has no member named ‘pack_job_id’
       __pyx_t_8 = __Pyx_PyInt_From_uint32_t(__pyx_v_self->_record->pack_job_id); if (unlikely(!__pyx_t_8)) __PYX_ERR(0, 2216, __pyx_L1_error)
                                                                  ^
pyslurm/pyslurm.c:29928:66: error: ‘slurm_job_info_t’ has no member named ‘pack_job_offset’
       __pyx_t_8 = __Pyx_PyInt_From_uint32_t(__pyx_v_self->_record->pack_job_offset); if (unlikely(!__pyx_t_8)) __PYX_ERR(0, 2217, __pyx_L1_error)
                                                                  ^
pyslurm/pyslurm.c:29949:39: error: ‘slurm_job_info_t’ has no member named ‘pack_job_id_set’
     __pyx_t_6 = (__pyx_v_self->_record->pack_job_id_set != 0);
                                       ^
pyslurm/pyslurm.c:29959:65: error: ‘slurm_job_info_t’ has no member named ‘pack_job_id_set’
       __pyx_t_8 = __Pyx_PyBytes_FromString(__pyx_v_self->_record->pack_job_id_set); if (unlikely(!__pyx_t_8)) __PYX_ERR(0, 2220, __pyx_L1_error)
                                                                 ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_3job_fill_job_desc_from_opts’:
pyslurm/pyslurm.c:36875:15: error: ‘job_desc_msg_t’ has no member named ‘ckpt_dir’
   __pyx_v_desc->ckpt_dir = slurm_get_checkpoint_dir();
               ^
pyslurm/pyslurm.c:36909:17: error: ‘job_desc_msg_t’ has no member named ‘ckpt_interval’
     __pyx_v_desc->ckpt_interval = ((uint16_t)__pyx_t_4);
                 ^
pyslurm/pyslurm.c:36929:17: error: ‘job_desc_msg_t’ has no member named ‘ckpt_interval’
     __pyx_v_desc->ckpt_interval = ((uint16_t)0);
                 ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_7jobstep___get’:
pyslurm/pyslurm.c:47339:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_8 = 0; __pyx_t_8 < __pyx_t_7; __pyx_t_8+=1) {
                                   ^
pyslurm/pyslurm.c:47888:106: error: ‘job_step_info_t’ has no member named ‘ckpt_dir’
       __pyx_t_12 = __pyx_f_7pyslurm_5slurm_stringOrNone((__pyx_v_job_step_info_ptr->job_steps[__pyx_v_i]).ckpt_dir, __pyx_kp_s_); if (unlikely(!__pyx_t_12)) __PYX_ERR(0, 
                                                                                                          ^
pyslurm/pyslurm.c:47900:95: error: ‘job_step_info_t’ has no member named ‘ckpt_interval’
       __pyx_t_12 = __Pyx_PyInt_From_uint16_t((__pyx_v_job_step_info_ptr->job_steps[__pyx_v_i]).ckpt_interval); if (unlikely(!__pyx_t_12)) __PYX_ERR(0, 3738, __pyx_L1_erro
                                                                                               ^
pyslurm/pyslurm.c: In function ‘__pyx_f_7pyslurm_7pyslurm_8topology___get’:
pyslurm/pyslurm.c:58406:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (__pyx_t_8 = 0; __pyx_t_8 < __pyx_t_7; __pyx_t_8+=1) {
                                   ^

`

**Comment by bikerdanny** [comment] 2020-03-19 21:40
I forked the repo (https://github.com/bikerdanny/pyslurm) and did some further changes.
It would be nice if the upgrade process was documented.
Then one could help better.

**Comment by giovtorres** [comment] 2020-03-20 12:33
I have a minimal set of notes in the wiki: https://github.com/PySlurm/pyslurm/wiki/Updating-PySlurm-for-New-Slurm-Releases. The `git diff` commands show the differences between the major versions.

All the C structs have to be updated between major versions. You can also look at previous commits that upgrade major releases.

I appreciate any contributions.

**Comment by bikerdanny** [comment] 2020-03-20 14:06
Thank you very much!

**Comment by mick-t** [comment] 2020-03-31 21:51
What's the best way to help? Create branch of the master branch or off the 19.05.0-v2 branch?

**Comment by giovtorres** [comment] 2020-04-03 01:14
Hi @mick-t , for starters, I need Slurm 20.02.0 working inside a test container. This is how I test locally. See this issue: https://groups.google.com/d/topic/slurm-users/GW6P5bHIpGQ/discussion

I have something wrong with my config. I've been using this config for several releases, but it's not working with the latest Slurm.

Have you gotten Slurm working inside a VM or container?

**Comment by giovtorres** [comment] 2020-04-03 02:00
With respect to the branches, the easier of the two is to branch off 19.05.0. It is currently in sync with master.

I'd really like to get v2 of the API going. I started but could never finish before a new version of Slurm released. v2 is faster and more Pythonic overall, using objects instead of dictionaries to access values.

If I can get Slurm 20.02.0 working locally, I will likely try to get v2 going again for the current version of Slurm and eventually deprecate v1 after the next release.

I'd appreciate any help with the project.

**Comment by mick-t** [comment] 2020-04-03 02:32
Hi Giovanni,

I'm not yet running Slurm 20.x and have just starting the process to upgrade my instance at work. I may not have a running instance to test for a while. 

Can I get a copy of your container or container definition?  I can see if I can run it and figure out your issues.

**Comment by giovtorres** [comment] 2020-04-03 02:52
> Can I get a copy of your container or container definition? I can see if I can run it and figure out your issues.

https://github.com/giovtorres/docker-centos7-slurm

**Comment by bikerdanny** [comment] 2020-04-08 10:51
Hello Giovanni,

I checked out your docker-centos7-slurm and build successully the new Slurm version 20.02.1.
docker build --build-arg SLURM_TAG="slurm-20-02-1-1" -t docker-centos7-slurm:20.02.1-1 .
docker run -it --name ernie --hostname ernie docker-centos7-slurm:20.02.1-1 bash
- Initializing database
- Updating MySQL directory permissions
- Starting MariaDB to create Slurm account database
200408 10:41:43 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
200408 10:41:43 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
- Starting MariaDB to create Slurm account database
- Starting MariaDB to create Slurm account database
- Creating Slurm acct database
- Slurm acct database created. Stopping MariaDB
- Starting all Slurm processes under supervisord
[root@ernie /]# sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST 
normal*      up 5-00:00:00      5   idle c[1-5] 
debug        up 5-00:00:00      5   down c[6-10] 
[root@ernie /]# srun hostname
ernie

If I use the parameter "-d" instead of "-it", than the container exited after your entrypoint script, because bash exit immediately.
I use the following in my docker container.
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["supervisord", "-c", "/etc/supervisord.conf", "--nodaemon"]

Best wishes,
Danny

**Comment by bikerdanny** [comment] 2020-04-08 11:01
...ok, I want to correct myself, as you wrote correctly in your docker-compose.yml, only a terminal (-t) is needed, so the following command also works for me.
docker run -dt --name ernie --hostname ernie docker-centos7-slurm:20.02.1-1

**Comment by bikerdanny** [comment] 2020-04-08 12:37
Do you use tools to generate the pxd file automatically?
https://github.com/cython/cython/wiki/AutoPxd

**Comment by bikerdanny** [comment] 2020-04-08 13:42
I first tried autopxd but the saw some errors with the included headers.
Than I switched to autopxd2, which is a fork of autopxd.
The following procedure created automatically a slurm.pxd from slurm.h.
docker run -it --name ernie --hostname ernie docker-centos7-slurm:20.02.1-1 bash
- Initializing database
- Updating MySQL directory permissions
- Starting MariaDB to create Slurm account database
200408 13:39:20 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
200408 13:39:21 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
- Starting MariaDB to create Slurm account database
- Creating Slurm acct database
- Slurm acct database created. Stopping MariaDB
- Starting all Slurm processes under supervisord
[root@ernie /]# pip3 install autopxd2
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting autopxd2
  Downloading https://files.pythonhosted.org/packages/ae/a8/8661f7591c9754a02e7b5e5a70f26499b6b18291e412a5dfc3ea1a6c44f7/autopxd2-1.1.0.tar.gz
Collecting six (from autopxd2)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting Click (from autopxd2)
  Downloading https://files.pythonhosted.org/packages/dd/c0/4d8f43a9b16e289f36478422031b8a63b54b6ac3b1ba605d602f10dd54d6/click-7.1.1-py2.py3-none-any.whl (82kB)
    100% |################################| 92kB 830kB/s 
Collecting pycparser (from autopxd2)
  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
    100% |################################| 112kB 1.6MB/s 
Installing collected packages: six, Click, pycparser, autopxd2
  Running setup.py install for autopxd2 ... done
Successfully installed Click-7.1.1 autopxd2-1.1.0 pycparser-2.20 six-1.14.0
[root@ernie /]# cd root/
[root@ernie ~]# export LC_ALL=en_US.UTF-8
[root@ernie ~]# export LANG=en_US.UTF-8
[root@ernie ~]# export LANGUAGE=en_US.UTF-8
[root@ernie ~]# autopxd --include-dir /usr/include /usr/include/slurm/slurm.h slurm.pxd
[root@ernie ~]# ll
total 84
-rw------- 1 root root  3323 Oct 24 16:09 anaconda-ks.cfg
-rw-r--r-- 1 root root 78768 Apr  8 13:41 slurm.pxd
[root@ernie ~]#

**Comment by giovtorres** [comment] 2020-04-11 23:27
>       [root@ernie /]# srun hostname
>       ernie

Could you try running `sbatch --wrap="sleep 60"`? I got it to compile just fine, but sbatch jobs were stuck in the CF state and would never actually proceed past that.

**Comment by giovtorres** [comment] 2020-04-11 23:27
> Do you use tools to generate the pxd file automatically?
> https://github.com/cython/cython/wiki/AutoPxd

No, haven't heard of it, but looks interesting! :eyes:

**Comment by bikerdanny** [comment] 2020-04-13 20:12
You are right, I also could not run the sbatch command.
I saw your post at the Slurm mailing list and found the following in the release note.
[...]
"NOTE: The FastSchedule option has been removed. The FastSchedule=2 functionality
      (used for testing and development) is available as the new
      SlurmdParameters=config_overrides option."
[...]
On the roadmap of Slurm 20.02 they also wrote, they removed the FastSchedule option and replaced the FastSchedule=2 functionality with the parameter SlurmdParameters=config_overrides.
So, I tested this also, but it does not work, too.
Maybe the --enable-front-end feature is broken in Slurm 20.02, I will test this tomorrow.
I also get a first version of PySlurm running with Slurm 20.02, I also will provide you my work tomorrow.
The tests are not all successfully, but I also work on that.
I used autopxd2 to convert slurm.h, slurmdb.h and slurm_errno.h.

**Comment by bikerdanny** [comment] 2020-04-14 18:21
After my colleague and I fought against the Slurm scheduler, I had some time to write a short documentation, how I bought PySlurm for Slurm 20.02.
Therefore I forked your repository and did some changes, this is only an idea how it could looks like.
https://github.com/bikerdanny/pyslurm/blob/20.02.1/BUILD.md

I also saw, that you already have another repo which uses many docker container for a Slurm cluster instead of emulating a bigger cluster with the parameter "--enable-front-end".
Did you tried that for building Slurm 20.02?
I also checked the command sbatch --wrap="hostname" on my Slurm cluster, which also consists of many container instead that parameter and it works fine.

**Comment by giovtorres** [comment] 2020-04-15 00:34
Hey, this looks amazing!! Thank you for taking the time to do this. I don't see where the patch files and the template files come from. I ran autopxd2 locally and it didn't produce any patch or .j2 files. Am I missing something?

**Comment by bikerdanny** [comment] 2020-04-15 02:50
The following is the content of my slurm.conf.
ClusterName=linux
ControlMachine=controller1
SlurmUser=slurm
SlurmdUser=root
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge
StateSaveLocation=/var/spool/slurm/slurmctld
SlurmdSpoolDir=/var/spool/slurm/slurmd
SwitchType=switch/none
MpiDefault=none
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid
ProctrackType=proctrack/pgid
ReturnToService=0
SlurmctldTimeout=300
SlurmdTimeout=300
InactiveLimit=0
MinJobAge=300
KillWait=30
Waittime=0
SchedulerType=sched/backfill
FastSchedule=1
SlurmctldDebug=3
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=3
SlurmdLogFile=/var/log/slurm/slurmd.log
JobCompType=jobcomp/none
AccountingStorageType=accounting_storage/slurmdbd
NodeName=compute1 Procs=1 State=UNKNOWN
PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP

**Comment by bikerdanny** [comment] 2020-04-22 20:04
Hi,

I've done some further changes on my forked PySlurm repository and I have got it to work for Slurm 20.02.
[root@c10 ~]# python3 $(which nosetests) -v pyslurm/tests
Config: Test config().get() return type. ... ok
Config: Test config().key_pairs() function and return type. ... ok
Config: Compare scontrol values to PySlurm values. ... ok
Hostlist: Create new hostlist ... ok
Hostlist: Test create empty hostlist. ... ok
Job: Test job().submit_batch_job(). ... ok
Job: Test job().get() return type. ... ok
Job: Test job().ids() return type. ... ok
Job: Test job count. ... ok
Job: Compare scontrol values to PySlurm values. ... ok
Job: Test job().find_user() (String). ... ok
Job: Test job().find_user() (Integer). ... ok
Job: Test job().slurm_kill_job(). ... ok
Jobstep: Test jobstep().get() return type. ... ok
Jobstep: Test jobstep().ids() return type. ... ok
Jobstep: Test jobstep count. ... ok
License: Test licenses().get() return type ... ok
License: Compare scontrol values to PySlurm values. ... ok
Misc: Test slurm_reconfigure() return. ... ok
Misc: Test slurm_api_version(). ... ok
Misc: Test slurm_load_slurmd_status(). ... ok
Node: Test node().get() return type. ... ok
Node: Test node().ids() return type. ... ok
Node: Test node count. ... ok
Node: Compare scontrol values to PySlurm values. ... ok
Node: Test node().update(). ... ok
Node: Test node().parse_gres(). ... ok
Partition: Test partition().get() return type. ... ok
Partition: Test partition().ids() return type. ... ok
Partition: Test partition count. ... ok
Partition: Compare scontrol values to PySlurm values. ... ok
Partition: Test partition().create(). ... ok
Partition: Test partition().update(). ... ok
Partition: Test partition().delete(). ... ok
QoS: Test get_qos() return type ... ok
Reservation: Test reservation().create(). ... ok
Reservation: Test reservation().get(). ... ok
Reservation: Test reservation().update(). ... ok
Reservation: Test reservation count. ... ok
Reservation: Compare scontrol values to PySlurm values. ... ok
Reservation: Test reservation().delete(). ... ok
Statistics: Test get_statistics() return type ... ok
Topology: Test get_topology() return type ... ok
Topology: Compare scontrol values to PySlurm values. ... ok
Slurmdb: Compare sacct and slurmdb_jobs.get() for all users ... ok
Slurmdb: Get jobs with steps for all users ... ok
Slurmdb: Compare sacct and slurmdb_jobs.get() for individual users ... ok

----------------------------------------------------------------------
Ran 47 tests in 16.837s

OK

Therefore I used the following description.
https://github.com/bikerdanny/pyslurm/blob/20.02.1/BUILD.md

Best wishes,
Danny

**Comment by mick-t** [comment] 2020-05-29 14:42
I have a dev cluster running 20.02.3 and can test updates/changes to pyslurm.

**Comment by mick-t** [comment] 2020-06-03 15:29
Hi,
acullenhms

**Comment by mick-t** [comment] 2020-06-03 15:31
Hi,

@acullenhms & I got @bikerdanny's 20.02 branch to build with Slurm 20.02.3 with minimal changes. We're testing it now and I'll let you know if there's any issues or problems. 

Thanks
--Mick

**Comment by acullenhms** [comment] 2020-06-04 19:26
@giovtorres @mick-t From what I can tell, bikerdanny's 20.02 branch seems to be working fine! Used it as a drop-in replacement for our stat collection dashboards and they started picking up (accurate) stats again from our dev cluster.

We're using it with Python2.7, which seems to output data a little bit differently than it does when run in Python3. So that, and a couple of our configuration settings, could explain the discrepancies in the unit tests above.

**Comment by giovtorres** [comment] 2020-06-08 01:54
Hi everyone. Sorry for the absence. It's been quite busy for me the past few months. I'm loving the collaboration here with testing!

@bikerdanny Would you mind doing a PR with your changes to get 20.02 merged in? I was able to verify as well locally a few weeks back, but I haven't found the time to update the test container. That is still on my todo list, unless someone wants to also do a PR there as well :wink:

**Comment by mick-t** [comment] 2020-06-08 22:26
@acullenhms bikerdanny's branch doesn't work for us as it uses Cython 0.19.2 and we only have Cython 0.19 on our Centos 7.7 nodes. I did a PR against @bikerdanny's branch:

https://github.com/bikerdanny/pyslurm/pulls

**Comment by Obihoernchen** [comment] 2020-06-10 23:26
@bikerdanny You need to do this using the GitHub web interface.
Just use this [link](https://github.com/PySlurm/pyslurm/compare/master...bikerdanny:20.02.1) and click "**Create pull request**" :)

**Comment by bikerdanny** [comment] 2020-06-11 19:58
@Obihoernchen: Thank you very much for your help. I used that link and created the following pull request.
https://github.com/PySlurm/pyslurm/pull/175

**Comment by granquet** [comment] 2021-01-20 15:24
Hello,
We would also be interested in getting pyslurm support for slurm 20.xx :)

Is there any way I can help to resume work on this topic?
I see multiple PRs on the subject, with the latest being https://github.com/PySlurm/pyslurm/pull/180

Thx,
Guillaume.

**Comment by baobablyh** [comment] 2021-03-22 23:33
Hi,

Thanks a lot for working on slurm20 support. We are going to upgrade the slurm to 20 soon, wondering when this is going to complete and merge to master?

Thanks!

**Comment by ahkumar** [comment] 2021-06-17 21:36
Hi All,

I would like to test pyslurm but we are currently at 20.11.xx. Hence I would like to add support to it on a branch is there an updated documentation on adding support? 

thanks!

**Comment by giovtorres** [comment] 2021-11-11 20:32
Both [20.02](https://github.com/PySlurm/pyslurm/releases/tag/20-02-5) and [20.11](https://github.com/PySlurm/pyslurm/releases/tag/v20.11.8-1) are now available.

**Comment by ahkumar** [comment] 2021-11-11 21:01
> Both [20.02](https://github.com/PySlurm/pyslurm/releases/tag/20-02-5) and [20.11](https://github.com/PySlurm/pyslurm/releases/tag/v20.11.8-1) are now available.

Is this support only available with python 3.9?  Ran into issues building with 3.6 hence the question. thanks!

**Comment by giovtorres** [comment] 2021-11-11 21:26
@ahkumar could you post the error you are getting. Python3.6 should work.

**Comment by giovtorres** [comment] 2021-11-12 13:41
@ahkumar could you open another issue for failing to build with 3.6. Please include steps to reproduce the error. I'll keep this issue closed. Thanks!

**Closed by giovtorres** 2021-11-12 13:41 UTC
Labels: Upgrade
